@signa_HostAddress = http://localhost:5000

POST {{signa_HostAddress}}/user/
Accept: application/json
Content-Type: application/json

{
  "id": {{$random.uuid}},
  "price": {{$random.integer()}},
  "ts": {{$timestamp}},
  "value": "content"
}

###
